---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: workload
  source:
    repoURL: 'https://github.com/UndeadDemidov/k3d-argocd-sandbox.git'
    targetRevision: library
    path: argocd/workload
    helm:
      parameters:
        - name: server
          value: https://kubernetes.default.svc
        - name: cluster
          value: in-cluster
        - name: project
          value: workload
        - name: ns
          value: workload
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
