# Global configuration
global:
  domain: argocd.local
  logging:
    format: json
  clusterConfig:
    enabled: true
    defaultCluster: "https://kubernetes.default.svc"

configs:
  cm:
    kustomize.buildOptions: --enable-helm

# Server configuration
server:
  service:
    type: NodePort
    nodePortHttp: 30080
    nodePortHttps: 30443
  extraArgs:
    - --insecure
  ingress:
    enabled: false

repoServer:
  livenessProbe:
    timeoutSeconds: 10
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 5
  readinessProbe:
    timeoutSeconds: 10
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 3
