namespace: "managed"
cluster: "in-cluster"
project: "managed"
path: "argocd/managed/workload/templates/secret-example.yaml"

secrets:
  - name: "managed-secret-example"
    type: "env"
    source: "some-secret.env"
